import re

CSL_VARIABLES = ['abstract', 'annote', 'archive', 'archive_location',
                 'archive-place', 'authority', 'call-number', 'citation-label',
                 'citation-number', 'collection-title', 'container-title',
                 'container-title-short', 'dimensions', 'DOI', 'event',
                 'event-place', 'first-reference-note-number', 'genre',
                 'ISBN', 'ISSN', 'jurisdiction', 'keyword', 'locator',
                 'medium', 'note', 'original-publisher',
                 'original-publisher-place', 'original-title', 'page',
                 'page-first', 'PMCID', 'PMID', 'publisher',
                 'publisher-place', 'references', 'reviewed-title',
                 'scale', 'section', 'source', 'status', 'title', 'title-short',
                 'URL', 'version', 'year-suffix', 'chapter-number',
                 'collection-number', 'edition', 'issue', 'number',
                 'number-of-pages', 'number-of-volumes', 'volume', 'accessed',
                 'container', 'event-date', 'issued', 'original-date',
                 'submitted', 'author', 'collection-editor', 'composer',
                 'container-author', 'director', 'editor', 'editorial-director',
                 'illustrator', 'interviewer', 'original-author', 'recipient',
                 'reviewed-author', 'translator', 'year', 'month', 'day']

CAPTURE_TEXT_BETWEEN_TAG_WITH_TRAILING_PUNCTUATION = re.compile(r"""<(?P<variable>abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)>
                                                                (?P<content>.*)
                                                                </\1>
                                                                (?P<trailing_chars>[^<(\w\s]*)
                                                                """, re.VERBOSE)

SPACE_PRECEDE_CLOSING_TAG = re.compile(r"\s{1}</(?P<variable>abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)>")

SPACE_FOLLOW_OPENING_TAG = re.compile(r"<(?P<variable>abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)>\s+")

LEFT_PARENTHESE = re.compile(r"(?P<leading>\()<(?P<variable>abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)>(?P<content>.*\)?\W?)</\2>")
DOUBLE_SPACE = re.compile(r"\s{2}")

CONNECTING_TAGS = re.compile(r"(<[^>])(abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)><(abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day>)([^<])")

TOKEN_AFTER_TAGS = re.compile(r"(<\/)(abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)(>)(\w+)")

HAS_TAG = re.compile(r"</?(?P<label>abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)>")

HAS_OPENING_TAG = re.compile(r"^<(?P<label>abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)>(?P<token>.*)$")

HAS_CLOSING_TAG = re.compile(r"^(?P<token>.*)</{1}(?P<label>abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)>$")

HAS_BOTH = re.compile(r"<(?P<label>abstract|annote|archive|archive_location|archive-place|authority|call-number|citation-label|citation-number|collection-title|container-title|container-title-short|dimensions|DOI|event|event-place|first-reference-note-number|genre|ISBN|ISSN|jurisdiction|keyword|locator|medium|note|original-publisher|original-publisher-place|original-title|page|page-first|PMCID|PMID|publisher|publisher-place|references|reviewed-title|scale|section|source|status|title|title-short|URL|version|year-suffix|chapter-number|collection-number|edition|issue|number|number-of-pages|number-of-volumes|volume|accessed|container|event-date|issued|original-date|submitted|author|collection-editor|composer|container-author|director|editor|editorial-director|illustrator|interviewer|original-author|recipient|reviewed-author|translator|year|month|day)>(?P<token>.*)</\1>")
